### ISSUE TITLE
Hamster. Счета. Невозможно изменить баланс счета на ноль. 

### ISSUE THREAD

**Issue by 1qwaka** [VK-BMSTU-QA/homework-2-spring-2024#108]
Приоритет: средний

URL: https://hammywallet.ru/accounts

Как воспроизвести:

1. Авторизоваться
2. Перейти по URL
3. Нажать на один из счетов в списке
5. В поле "Сколько там сейчас денег?" поменять значение на ноль
6. Нажать на кнопку "Сохранить"

Ожидаемый результат: Баланс счета изменится на ноль.
Фактический результат: В поле баланса счета появляется ошибка "Число не может начинаться с 0".

Скриншот:
![image](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/70287659/f9b20094-c1c0-42d9-b488-af0e32b97775)

**Comment by CodeMaster482** [comment]
Approve

**Comment by DmitriyKomarovCoder** [comment]
Approve

**Comment by Gallaann** [comment]
Аппрув

**Comment by Dellvin** [comment]
аппрув
