### ISSUE TITLE
PinSpire. Навигация. Вместо отображения “404-ой” страницы при попытке получить несуществующий профиль отображается страница с пустым основным содержимым.

### ISSUE THREAD

**Issue by muslimitsuhide** [VK-BMSTU-QA/homework-2-spring-2024#135]
Приоритет: средний
URL: https://pinspire.site/user/<user_id>

Как воспроизвести:

1. Ввести в адресной строке адрес вида https://pinspire.site/user/<user_id>, где user_id - id несуществующего пользователя;

**Ожидаемый результат**: отображение 404-ой страницы “Страница не обнаружена”.

**Фактический результат**: отображение страницы с шапкой и sidebar’ом с пустым “телом” (содержимым).

![navigation_12_1](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/82032430/60a7e7b2-952a-4b5d-b754-e085c90002fa)

![navigation_12_2](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/82032430/c1c02246-3fe5-47ce-abf9-c4191820bd4d)

**Comment by DriverOnLips** [comment]
approved

**Comment by Gvidow** [comment]
approved

**Comment by wonderf00l** [comment]
approved
