### ISSUE TITLE
PinSpire. Пины. Не работает drag&drop.

### ISSUE THREAD

**Issue by muslimitsuhide** [VK-BMSTU-QA/homework-2-spring-2024#139]
**Приоритет**: средний
**URL**: https://pinspire.site/create/pin

**Как воспроизвести**:

1. Войти в аккаунт;
2. Нажать на кнопку "Создать пин";
3. Перетащить картинку в поле выбора;

**Ожидаемый результат**: картинка загрузится на сайт.
**Фактический результат**: картинка не загружается на сайт.

**Comment by DriverOnLips** [comment]
approved

**Comment by Gvidow** [comment]
approved

**Comment by wonderf00l** [comment]
approved

**Comment by BeeHeather** [comment]
Аппрув
