### ISSUE TITLE
PinSpire. Страница ленты. Неавторизованный пользователь. При быстром скролле вниз пины не успевают прогрузиться и приходится находится на пустой странице какое-то время.

### ISSUE THREAD

**Issue by muslimitsuhide** [VK-BMSTU-QA/homework-2-spring-2024#141]
**Приоритет**: средний
**URL**: https://pinspire.site/

**Как воспроизвести**:

1. Перейти на страницу ленты;
2. Начать быстро скроллить вниз.

**Ожидаемый результат**: загрузка новых пинов.
**Фактический результат**: пины не успели прогрузиться, видна только пустая лента.

![main_1](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/82032430/62568159-1e79-4532-a922-6e7fac47c90c)

**Comment by DriverOnLips** [comment]
approved

**Comment by Gvidow** [comment]
approved

**Comment by wonderf00l** [comment]
approved

**Comment by BeeHeather** [comment]
Аппрув
