### ISSUE TITLE
PinSpire. Функционал лайков и комментариев. Присутствуют случаи ошибочной фильтрации текста без ненормативной лексики в комментариях.

### ISSUE THREAD

**Issue by muslimitsuhide** [VK-BMSTU-QA/homework-2-spring-2024#145]
**Приоритет**: средний
**URL**: https://pinspire.site/pin/{pinID}

**Как воспроизвести**:

1. Войти в аккаунт;
2. Перейти на страницу пина;
3. Написать комментарий без ненормативной лексики;

**Ожидаемый результат**: публикация комментария без замены слов на символы "\*".
**Фактический результат**:  возможна замена некоторых слов на символы "\*".

**Comment by DriverOnLips** [comment]
approved

**Comment by Gvidow** [comment]
approved

**Comment by wonderf00l** [comment]
approved
