### ISSUE TITLE
PinSpire. Уведомления. Проблема с оповещением о новом уведомлении в случае если у пользователя они уже есть. 

### ISSUE THREAD

**Issue by muslimitsuhide** [VK-BMSTU-QA/homework-2-spring-2024#146]
**Приоритет**: средний
**URL**: https://pinspire.site

**Как воспроизвести**:

1. Войти в аккаунт;
2. Получать сообщения от другого пользователя;

**Ожидаемый результат**: изменение числа непрочитанных уведомлений у значка уведомлений
**Фактический результат**:  неизменное состояние значка уведомлений (колокольчик с точкой) после получения первого сообщения

**Comment by DriverOnLips** [comment]
approved

**Comment by Gvidow** [comment]
approved

**Comment by wonderf00l** [comment]
approved

**Comment by BeeHeather** [comment]
Аппрув
