### ISSUE TITLE
PinSpire. Подписки. Выход символов за пределы input поля для фильтрации подписок.

### ISSUE THREAD

**Issue by muslimitsuhide** [VK-BMSTU-QA/homework-2-spring-2024#150]
**Приоритет**: средний
**URL**: https://pinspire.site/subscriptions

**Как воспроизвести**:

1. Войти в аккаунт;
2. Перейти на страницу подписок;
3. Ввести в input поле последовательность символов, длина которой превышает размеры этого поля;

**Ожидаемый результат**: затирание начальных символов так, чтобы введенная строка полностью вмещалась в 
 input поле.
**Фактический результат**: затирание начальных символов, но введенная строка выступает на один символ из input поля.

**Comment by DriverOnLips** [comment]
approved

**Comment by Gvidow** [comment]
approved

**Comment by wonderf00l** [comment]
approved

**Comment by BeeHeather** [comment]
Аппрув
