### ISSUE TITLE
Hamster. Дэшборд. Отображение транзакций с большой разницей на графииках

### ISSUE THREAD

**Issue by CodeMaster482** [VK-BMSTU-QA/homework-2-spring-2024#155]
Приоритет: низкий

URL: https://hammywallet.ru/

Как воспроизвести:

    1. Авторизоваться
    2. Создать транзакцию суммой до 100 руб.
    3. Создать транзакцию суммой больше 10000 руб.
    4. Перейти по URL
    5. Навестисть на транзакцию с меньшей суммой
Ожидаемый результат: Отображение транзакции с меньшей суммой видно на графиках хорошо, с ней можно взаимодействовать
Фактический результат: На графиках деление транзакции с меньшей суммой сложно или невозможно увидеть ( в зависимости от разницы) с ней нельзя или сложно взаимодействовать те наводиться на нее не отображается описании на графике

**Comment by DmitriyKomarovCoder** [comment]
Аппрув, но скрина не хватает

**Comment by DmitriyKomarovCoder** [comment]
Аппрув

**Comment by Dellvin** [comment]
нужен скрин
