### ISSUE TITLE
Фанаты Ёлки. Профиль. Загрузка гифок в качестве аватарок.

### ISSUE THREAD

**Issue by kek-flip** [VK-BMSTU-QA/homework-2-spring-2024#16]
### URL

- https://prinesy-poday.ru/me

### Приоритет

- minor

### Окружение

- Браузер _Google Chrome 121.0.6167.185_
- ОС _Windows 10_

### Описание
**Шаги воспроизведения**:

1. Авторизоваться
2. Перейти в профиль
3. Нажать на аватарку
4. Загрузить файл с расширением .gif
5. Нажать "Сохранить"

**Текущее поведение**

Можно установить гифку в качестве аватарки, причем она будет проигрываться и в профиле, и в навбаре

**Ожидаемое поведение**

При попытке загрузить гифку пользователь получает соответствующую ошибку

**Comment by wizardOfOz21** [comment]
Выше есть более общий баг, не вижу в этом смысла

**Comment by tomsuliana** [comment]
Согласна с Гамидом

**Comment by wizardOfOz21** [comment]
> В отличие от файлов, не являющихся изображением, гифки отображаются как обычные аватарки и не ломают пользовательский опыт, поэтому я вынес гифки в отдельный баг с низким приоритетом

Может это и не баг тогда?

**Comment by wizardOfOz21** [comment]
Не принципиальный вопрос, апрув

**Comment by kek-flip** [comment]
> > В отличие от файлов, не являющихся изображением, гифки отображаются как обычные аватарки и не ломают пользовательский опыт, поэтому я вынес гифки в отдельный баг с низким приоритетом
> 
> Может это и не баг тогда?

Вот и я этим вопросом задаюсь

**Comment by kek-flip** [comment]
Данный баг был включен в баг #17
