### ISSUE TITLE
Komisaki. Список опросов. При вводе огромного сообщение в поле поиска сервис падает.

### ISSUE THREAD

**Issue by Antihoman** [VK-BMSTU-QA/homework-2-spring-2024#160]
**Приоритет**: блокер

**URL**: https://formhub.site/forms

**Как воспроизвести**:

1. Авторизоваться
2. Перейти по URL
3. В поле "Поиск" ввести длинное сообщение и продолжить копировать и вставлять его некоторое время
4. После некоторого времени попытаться обработать запрос сервис выдать "нет подключения к сети"

**Ожидаемый результат**: Должна появится ошибка о превышении лимита символов
**Фактический результат**: Падение сервиса

**Скриншот**:
![image](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/91897029/24ee7d55-c4a2-4e08-8926-7d83ca3ee355)

**Comment by rissenberg** [comment]
Approve

**Comment by AlexnadrLarin** [comment]
Апрув

**Comment by Dellvin** [comment]
выделить жирным заголовки

**Comment by Dellvin** [comment]
добавить списки

**Comment by Dellvin** [comment]
аппрув
