### ISSUE TITLE
Komisaki. Список опросов. При вводе спецсимвола в поле поиска не выдается ошибка.

### ISSUE THREAD

**Issue by Antihoman** [VK-BMSTU-QA/homework-2-spring-2024#161]
**Приоритет**: низкий

**URL**: https://formhub.site/forms

**Как воспроизвести**:

1. Авторизоваться
2. Перейти по URL
3. В поле "Поиск" ввести спецсимвол

**Ожидаемый результат**: Должна появится ошибка о недопустимости спецсимволов
**Фактический результат**: Ошибка не появилась, а спецсимвол пропущен

**Скриншот**: 
![image](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/91897029/fc527c76-a27f-4dc5-bc2b-0399fe5bed57)

**Comment by rissenberg** [comment]
Approve

**Comment by AlexnadrLarin** [comment]
Апрув

**Comment by Dellvin** [comment]
выделить жирным заголовки, и приоритет средний или низкий

**Comment by Dellvin** [comment]
добавить списки

**Comment by Dellvin** [comment]
аппрув
