### ISSUE TITLE
Komisaki. Просмотр опроса. Переход по ссылке на просмотр определенного опроса.

### ISSUE THREAD

**Issue by Antihoman** [VK-BMSTU-QA/homework-2-spring-2024#162]
**Приоритет**: крит

**URL**: https://formhub.site/forms/1

**Как воспроизвести**:

1. Авторизоваться
2. Перейти по URL
3. Далее менять цифры в конце ссылки, тем самым попадая на чужие опросы

**Ожидаемый результат**: Айди опросов должны быть зашифрованы
**Фактический результат**: Айди опросов являются обычными цифрами 

**Скриншот**: 
![image](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/91897029/3235abf4-4669-4af4-993f-82d6aff84cbf)

**Comment by rissenberg** [comment]
Approve

**Comment by AlexnadrLarin** [comment]
Апрув

**Comment by Dellvin** [comment]
выделить жирным заголовки, я бы поставил крит

**Comment by Dellvin** [comment]
добавить списки

**Comment by Dellvin** [comment]
аппрув
