### ISSUE TITLE
Komisaki. Прохождение опроса. Отсутствие xss экранирования в поле тестового ответа.

### ISSUE THREAD

**Issue by Antihoman** [VK-BMSTU-QA/homework-2-spring-2024#163]
**Приоритет**: блокер

**URL**: https://formhub.site/forms/55

**Как воспроизвести**:

1. Перейти по URL
2. В поле "Развернутый ответ" ввести спецсимвол или sql/js инъекцию.

**Ожидаемый результат**: Должна появится ошибка о недопустимых символах
**Фактический результат**: Ошибки нет - спецсимволы пропущены

**Скриншот**: 
![image](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/91897029/5e0eca88-98c9-42c7-bafe-2c6121157631)

**Comment by rissenberg** [comment]
Approve

**Comment by AlexnadrLarin** [comment]
Апрув

**Comment by Dellvin** [comment]
выделить жирным заголовки, описание не совпадает названием

**Comment by Dellvin** [comment]
добавить списки

**Comment by Dellvin** [comment]
аппрув
