### ISSUE TITLE
Komisaki. Прохождение опросов. При вводе вопроса автору опроса нет валидации символов.

### ISSUE THREAD

**Issue by Antihoman** [VK-BMSTU-QA/homework-2-spring-2024#164]
**Приоритет**: средний

**URL**: https://formhub.site/forms/55

**Как воспроизвести**:

1. Авторизоваться
2. Перейти по URL или перейти на любой другой опрос
3. Нажать кнопку "Задать вопрос"
4. В открывшемся окне ввести спецсимволы или инъекцию

**Ожидаемый результат**: Должна появится ошибка о недопустимых символах
**Фактический результат**: Ошибки нет и спецсимвол пропущен валидацией

**Скриншот**:
![image](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/91897029/256c74df-135e-4bbc-bbcd-1ead4aef49d4)

**Comment by rissenberg** [comment]
Approve

**Comment by AlexnadrLarin** [comment]
Апрув

**Comment by Dellvin** [comment]
выделить жирным заголовки

**Comment by Dellvin** [comment]
добавить списки

**Comment by Dellvin** [comment]
приоритет стандартный

**Comment by Dellvin** [comment]
аппрув
