### ISSUE TITLE
Komisaki. Чат. При отправке длинного сообщения ломается верстка.

### ISSUE THREAD

**Issue by Antihoman** [VK-BMSTU-QA/homework-2-spring-2024#165]
**Приоритет**: низкий

**URL**: https://formhub.site/forms/55

**Как воспроизвести**:

1. Авторизоваться
2. Перейти по URL или перейти на любой другой опрос
3. Нажать кнопку "Задать вопрос"
4. В открывшемся окне ввести любое сообщение
5. Далее окажитесь в чате с автором поста
6. Ввести очень длинное сообщение и отправить его

**Ожидаемый результат**: Поле сообщение имеет ограничение по символам и не допустит очень длинного сообщения, а также будет перенос строки у этого сообщения
**Фактический результат**: Поле сообщения не имеет ограничения по символам и все символы свыше определенного числа уйдут за окно и не будут никак видны

**Скриншот**:
![image](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/91897029/26fd24a1-f686-43f2-92a5-c1588fbb8539)

**Comment by rissenberg** [comment]
Approve

**Comment by AlexnadrLarin** [comment]
Апрув

**Comment by AlexnadrLarin** [comment]
Апрув

**Comment by Dellvin** [comment]
Изменить описание

**Comment by Dellvin** [comment]
добавить списки

**Comment by Dellvin** [comment]
аппрув
