### ISSUE TITLE
Komisaki. Логин. При нажатии кнопки "Назад" после входа снова открывается окно логина.

### ISSUE THREAD

**Issue by AlexnadrLarin** [VK-BMSTU-QA/homework-2-spring-2024#166]
**Приоритет:** низкий

**URL:** https://formhub.site/login

**Порядок действий:**
1. Авторизироваться
2. Нажать кнопку "Вернуться назад" в браузере

**Ожидаемый результат:** Редирект на страницу логина не должен произойти. Пользователь должен остаться на странице "Мои опросы".
**Фактический результат:** Происходит редирект на страницу логина и можно повторно войти. В шапке профиля появляется аватарка и имя пользователя, которые не должны появляться на странице логина.

**Скриншот:**
![image](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/47739783/9b932102-a3e4-456e-85f9-b063b4646d08)

**Comment by rissenberg** [comment]
Approve

**Comment by Dellvin** [comment]
выделить жирным заголовки

**Comment by Dellvin** [comment]
укоротить название
понизить приоритет

**Comment by Dellvin** [comment]
списки

**Comment by Dellvin** [comment]
аппрув
