### ISSUE TITLE
Komisaki. Регистрация. При нажатии кнопки "Назад" после регистрации снова откроется окно регистрации.

### ISSUE THREAD

**Issue by AlexnadrLarin** [VK-BMSTU-QA/homework-2-spring-2024#167]
**Приоритет:** низкий

**URL:** https://formhub.site/signup

**Порядок действий:**
1. Зарегистрироваться
2. Нажать кнопку "Вернуться назад" в браузере

**Ожидаемый результат:** Редирект на страницу регистрации не должен произойти. Пользователь должен остаться на странице "Мои опросы".
**Фактический результат:** Происходит редирект на страницу регистрации и можно повторно зарегистрироваться. В шапке профиля появляется аватарка и имя пользователя, которые не должны появляться на странице регистрации.

**Скриншот:**
![image](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/47739783/151cdc4f-6bd0-42f3-b18c-4a5651d41d1e)

**Comment by Antihoman** [comment]
Approve

**Comment by rissenberg** [comment]
Approve

**Comment by Dellvin** [comment]
нужно жирным выделить заголовки

**Comment by Dellvin** [comment]
слишком длинное описание, надо укоротить
поменять приоритет

**Comment by Dellvin** [comment]
списки

**Comment by Dellvin** [comment]
аппрув
