### ISSUE TITLE
Komisaki. Редактирование профиля. При изменении username и нажатии кнопки "Сохранить" появляется ошибка сервера.

### ISSUE THREAD

**Issue by AlexnadrLarin** [VK-BMSTU-QA/homework-2-spring-2024#168]
**Приоритет:** средний

**URL:** https://formhub.site/profile/update

**Порядок действий:**
1. Авторизироваться
2. Перейти по URL
3. Изменить username
4. Нажать кнопку "Сохранить"

**Ожидаемый результат:** После нажатия кнопки "Сохранить" должен произойти редирект на страницу профиля пользователя и измениться ник.
**Фактический результат:** После нажатия кнопки "Сохранить"  выдается ошибка сервера.

**Скриншот:**
![image](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/47739783/0647ffd4-8d9b-4f21-9e66-a41e43fe083e)

**Comment by Antihoman** [comment]
Approve

**Comment by rissenberg** [comment]
Approve
