### ISSUE TITLE
Komisaki. Редактирование профиля. При изменении старого пароля и нажатии кнопки "Сохранить" выдается другая ошибка.

### ISSUE THREAD

**Issue by AlexnadrLarin** [VK-BMSTU-QA/homework-2-spring-2024#169]
**Приоритет**: средний

**URL:** https://formhub.site/profile/update

**Порядок действий:**
1. Авторизироваться
2. Перейти по URL
3. Изменить старый пароль
4. Нажать кнопку "Сохранить"

**Ожидаемый результат:** После нажатия кнопки "Сохранить" должна высветиться ошибка о запрете смены старого пароля. 
**Фактический результат:** После нажатия кнопки "Сохранить" высвечивается ошибка сервера.

**Скриншот:**
![image](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/47739783/087f565a-dc43-40c8-b9d6-30970520cbe3)

**Comment by Antihoman** [comment]
Approve

**Comment by rissenberg** [comment]
Approve

**Comment by Dellvin** [comment]
слишком длинное описание

**Comment by Dellvin** [comment]
аппрув
