### ISSUE TITLE
Komisaki. Редактирование опроса. После достижения лимита по ответам, кнопка "Добавить ответ" пропадает навсегда

### ISSUE THREAD

**Issue by rissenberg** [VK-BMSTU-QA/homework-2-spring-2024#174]
**Приоритет:**  Средний

**URL:**  https://formhub.site/forms/new

**Как воспроизвести:**
Авторизоваться;
Перейти по URL;
На карточке любого вопроса прокликать кнопку "Добавить ответ" 11 раз, после чего она пропадет;
Удалить один или несколько созданных ответов.

**Ожидаемый результат:** После удаления одного из 12 ответов, кнопка "Добавить ответ" должна вновь отобразиться.
**Фактический результат:**  После удаления ответов, кнопка "Добавить ответ" не отображается.

**Скриншот:**
![image](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/114286666/52568aa6-5411-4f02-a113-f41bd6022e0d)

**Comment by Antihoman** [comment]
Approve

**Comment by AlexnadrLarin** [comment]
Апрув

**Comment by Dellvin** [comment]
аппрув
