### ISSUE TITLE
Komisaki. Редактирование опроса. При сохранении, пустые поля ответов не подсвечиваются красным

### ISSUE THREAD

**Issue by rissenberg** [VK-BMSTU-QA/homework-2-spring-2024#175]
**Приоритет:**  Средний

**URL:**  https://formhub.site/forms/new

**Как воспроизвести:**
Авторизоваться;
Перейти по URL;
Нажать кнопку "Создать".

**Ожидаемый результат:** Отображается ошибка "Введены не все данные. Проверьте правильность заполнения.", все обязательные незаполненные поля подсвечиваются красным цветом.
**Фактический результат:** Отображается ошибка "Введены не все данные. Проверьте правильность заполнения.", все обязательные незаполненные поля подсвечиваются красным цветом, **кроме полей ответов**.

**Скриншот:**
![image](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/114286666/bd8ca70f-75d3-4329-87db-f8f74306e902)

**Comment by Antihoman** [comment]
Approve

**Comment by AlexnadrLarin** [comment]
Апрув

**Comment by Dellvin** [comment]
аппрув
