### ISSUE TITLE
Komisaki. Результаты опроса. Статистика по участникам всегда отображает 0 участников

### ISSUE THREAD

**Issue by rissenberg** [VK-BMSTU-QA/homework-2-spring-2024#176]
**Приоритет**: Стандартный

**URL:** https://formhub.site/forms/56/results

**Как воспроизвести:**
Авторизоваться под тестовым профилем:
```
tester@test.com
```
```
password
```
Перейти по URL. Предварительно был создан неанонимный опрос, включающий в себя 1 вопрос. С двух разных аккаунтов были произведены 3 прохождения этого опроса, что отображено в первой карточке результатов;

**Ожидаемый результат:** В карточках "Статистика по участникам" отображается 2 участника.
**Фактический результат:** В карточках "Статистика по участникам" отображается 0 участников.

Скриншот:
![image](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/114286666/a98362c7-13b9-45dd-929d-78c1da5d70a6)

**Comment by Antihoman** [comment]
Approve

**Comment by AlexnadrLarin** [comment]
Апрув

**Comment by Dellvin** [comment]
приоритет стандартный

**Comment by Dellvin** [comment]
аппрув
