### ISSUE TITLE
Работяги из Чайхоны. Лента на главной странице & лента по тегу. Все посты отображаются с датой 0001.01.01 00:00

### ISSUE THREAD

**Issue by Vilinvil** [VK-BMSTU-QA/homework-2-spring-2024#183]
**Приоритет:** Высокий
**Окружение:**  Chrome Version 122.0.6261.111 (Official Build) (64-bit)
**URL:** https://my-kopilka.ru/feed

**Шаги воспроизведения:**
1. Авторизоваться/зарегестриоваться 
2. Подписаться на любого автора. Пр: Баринов https://my-kopilka.ru/profile2
3. Перейти на главную ленту https://my-kopilka.ru/feed
(В ленте по тегам, такой же баг, для воспроизведения нужно нажать на любой тег в посте)

**Фактический результат:** 
В ленте в запросе постов приходят все посты с датой создания 0001.01.01 00:00 и соответственно не в правильном порядке отображаются.
![bug_date_time_in_post](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/98636591/856f4a80-ecf6-4846-910a-944313aaded2)

хотя при переходе в ленту отдельного автора даты отображаются в соответстивии с датой создния автором 
![bug_date_time_in_post_2](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/98636591/3e22d485-bbaf-4e6e-9d2e-25e9f3d711ab)

**Ожидаемый результат:**
Даты в главной ленте, в ленте по тегу, в ленте автора будут совпадать и будут отображаться новые посты выше

**Comment by SanExpett** [comment]
апрув

**Comment by sachatarba** [comment]
апрув

**Comment by M0rdovorot** [comment]
апрув

**Comment by sachatarba** [comment]
апрув

**Comment by alexey-ershkov** [comment]
Аппрув
