### ISSUE TITLE
Работяги из Чайхоны. Профиль донатера. Надпись "пожертвовано" отображается не полностью в случае 0 руб

### ISSUE THREAD

**Issue by Vilinvil** [VK-BMSTU-QA/homework-2-spring-2024#190]
**Приоритет:** Низкий
**Окружение:** Chrome Version 122.0.6261.111 (Official Build) (64-bit)
**URL:** https://my-kopilka.ru/profile24

**Шаги воспроизведения:**
1. Войти как донатер https://my-kopilka.ru/login
Логин: vilin_donater
Пароль: 1234!@#$qwerQWER
2. Перейти на страницу профиля https://my-kopilka.ru/profile24

**Фактический результат:** 
Пишется только слово "Пожертвовано"

![bug_donated](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/98636591/79e6f9e1-f4db-4958-96b0-78ad4bd65be9)

**Ожидаемый результат:**
Показывается ничего или "пожертвавоно 0 руб " пользователю, чтобы не запутывать его.

**Comment by SanExpett** [comment]
апрув

**Comment by M0rdovorot** [comment]
апрув

**Comment by sachatarba** [comment]
апрув

**Comment by alexey-ershkov** [comment]
аппрув
