### ISSUE TITLE
Работяги из Чайхоны. Профиль донатера. Нет отображения подсказки в случае отсутвия подписок.

### ISSUE THREAD

**Issue by Vilinvil** [VK-BMSTU-QA/homework-2-spring-2024#192]
**Приоритет:** Низкий
**Окружение:** Chrome Version 122.0.6261.111 (Official Build) (64-bit)
**URL:** https://my-kopilka.ru/profile24

**Шаги воспроизведения:**
1. Войти как донатер https://my-kopilka.ru/login
Логин: vilin_donater
Пароль: 1234!@#$qwerQWER

2. Перейти на страницу профиля https://my-kopilka.ru/profile24

**Фактический результат:**
Надпись "подписки"

![bug_empty_subscriptions](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/98636591/ff23e17d-ffe6-444b-8ffa-f166eeec93a8)

**Ожидаемый результат:**
Надпись "у вас нет подписок" или "вы еще ни на кого не подписаны", иначе может
  запутать пользователя

**Comment by SanExpett** [comment]
апрув

**Comment by M0rdovorot** [comment]
апрув

**Comment by sachatarba** [comment]
апрув

**Comment by sachatarba** [comment]
апрув

**Comment by alexey-ershkov** [comment]
аппрув
