### ISSUE TITLE
Работяги из Чайхоны. Профиль донатера. Надпись подписки съезжает вниз бокса.

### ISSUE THREAD

**Issue by Vilinvil** [VK-BMSTU-QA/homework-2-spring-2024#193]
**Приоритет:** Низкий
**Окружение:** Chrome Version 122.0.6261.111 (Official Build) (64-bit)
**URL:** https://my-kopilka.ru/profile24

**Шаги воспроизведения:**
1. Войти как донатер https://my-kopilka.ru/login
Логин: vilin_donater
Пароль: 1234!@#$qwerQWER
2. Перейти на страницу профиля https://my-kopilka.ru/profile24

**Фактический результат:**
Надпись "подписки" расположена снизу блока

![bug_empty_subscriptions](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/98636591/7e520e5d-a17a-4d99-8aac-aa8c08a57178)

**Ожидаемый результат:**
Надпись "подписки" расположена по центру блока

**Comment by SanExpett** [comment]
апрув

**Comment by M0rdovorot** [comment]
апрув

**Comment by alexey-ershkov** [comment]
аппрув
