### ISSUE TITLE
Работяги из Чайхоны. Профиль донатера & автора. Окно редактирования статуса(об авторе) не гаснет при нажатии вне него.

### ISSUE THREAD

**Issue by Vilinvil** [VK-BMSTU-QA/homework-2-spring-2024#194]
**Приоритет:** Низкий
**Окружение:** Chrome Version 122.0.6261.111 (Official Build) (64-bit)
**URL:** https://my-kopilka.ru/profile24 и https://my-kopilka.ru/profile26

**Шаги воспроизведения:**
1. Войти как донатер https://my-kopilka.ru/login (у автора такой же баг)
Логин: vilin_donater или vilin_author
Пароль: 1234!@#$qwerQWER
2. Перейти на страницу профиля https://my-kopilka.ru/profile24
3. Нажать на шестеренку редактирования статуса или об авторе.

**Фактический результат:**
При нажатии вне всплывающего окна редактирования статуса ничего не происходит

**Ожидаемый результат:**
Предпологается, что окно будет закрываться, т.к. это общепринаятое и ожидаемое поведение

**Comment by SanExpett** [comment]
апрув

**Comment by M0rdovorot** [comment]
апрув

**Comment by alexey-ershkov** [comment]
аппрув
