### ISSUE TITLE
Работяги из Чайхоны. Авторизация. Кнопка "Забыли пароль?" ведет на 404.

### ISSUE THREAD

**Issue by SanExpett** [VK-BMSTU-QA/homework-2-spring-2024#195]
**Приоритет:** Высокий
**Окружение:** Chrome Version 122.0.6261.111 (Official Build) (64-bit)
**URL:** https://my-kopilka.ru/login

#### Шаги воспроизведения:
1. Перейти на страницу https://my-kopilka.ru/login
2. Нажать кнопку "Забыли пароль?"

#### Фактический результат
Страница 404
![image](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/118511246/b67529c6-ee9a-4a9d-8ce2-49182512acce)

#### Ожидаемый результат 
Страница восстановления пароля.

**Comment by Vilinvil** [comment]
апрув

**Comment by M0rdovorot** [comment]
апрув

**Comment by sachatarba** [comment]
апрув
