### ISSUE TITLE
Работяги из Чайхоны. Профиль донатера & автора. Уязвимость DOM XSS в поле статуса и поле об авторе.

### ISSUE THREAD

**Issue by Vilinvil** [VK-BMSTU-QA/homework-2-spring-2024#196]
**Приоритет:** Средний
**Окружение:** Chrome Version 122.0.6261.111 (Official Build) (64-bit)
**URL:** https://my-kopilka.ru/profile26 или URL: https://my-kopilka.ru/profile24

**Шаги воспроизведения:**
1. Войти в аккаунта автора  https://my-kopilka.ru/login (у донатера тоже баг)
Логин: vilin_author или vilin_donater
Пароль: 1234!@#$qwerQWER
2. Перейти на страницу профиля https://my-kopilka.ru/profile26
3. Нажать на шестеренку редактирования статуса или об авторе.
4. Вставить в поле текст
```
5sas <img src="image.gif" onerror="alert(123)">df
```

**Фактический результат:**

Код исполняется и вставляется в верстку

![vulnerability_status](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/98636591/1352b2a1-9384-4a94-8ab3-1a5519ac3ff1)

А при перезагрузке уже просто как текст
![vulnerability_status_2](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/98636591/846546f1-bd3e-45ef-84bf-68046fdfd3a6)

**Ожидаемый результат:**
Входное значение будет вставляться как строка, а не добавляться в верстку.

**Comment by SanExpett** [comment]
апрув

**Comment by M0rdovorot** [comment]
апрув

**Comment by sachatarba** [comment]
апрувв

**Comment by alexey-ershkov** [comment]
Аппрув
