### ISSUE TITLE
Работяги из Чайхоны. Комментарии. Слишком длинный комментарий без пробелов не вмещается в экран и не переносится на следующую строку.

### ISSUE THREAD

**Issue by SanExpett** [VK-BMSTU-QA/homework-2-spring-2024#197]
**Приоритет:** Средний
**Окружение:** Chrome Version 122.0.6261.111 (Official Build) (64-bit)
**URL:** https://my-kopilka.ru/profile2

#### Шаги воспроизведения 
1. Авторизуемся (логин - SanExpett, пароль - passworD1^^) https://my-kopilka.ru/login
2. Перейдем на страницу какого-либо автора. Например https://my-kopilka.ru/profile2
3. Выберем пост и оставим длинный комментарий (длиннее одного экрана) и без пробелов.

#### Фактический результат
Комментарий не влезает в экран и выходит за отведенное для комментария поле.
![image](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/118511246/1b94d02d-d281-476f-9ee2-9b76cadadd02)

#### Ожидаемый результат
Комментарий разделяется и переносится так, чтобы поместиться в отведенное для комментария поле

**Comment by Vilinvil** [comment]
апрув

**Comment by M0rdovorot** [comment]
апрув

**Comment by alexey-ershkov** [comment]
Аппрув
