### ISSUE TITLE
Работяги из Чайхоны. Профиль донатера & автора. Неправильная иконка редактирования "статуса" и "об авторе"

### ISSUE THREAD

**Issue by Vilinvil** [VK-BMSTU-QA/homework-2-spring-2024#198]
**Приоритет:** Низкий
**Окружение:** Chrome Version 122.0.6261.111 (Official Build) (64-bit)

**Шаги воспроизведения:**
1. Войти как донатер https://my-kopilka.ru/login (у автора тоже баг)
Логин: vilin_donater
Пароль: 1234!@#$qwerQWER
2. Перейти на страницу профиля https://my-kopilka.ru/profile24

**Фактический результат:**
Отображается шестеренка в качестве иконки редактирования. 

**Ожидаемый результат:**
Отображается иконка карандаша.

**Comment by SanExpett** [comment]
апрув

**Comment by M0rdovorot** [comment]
апрув

**Comment by sachatarba** [comment]
апрув

**Comment by Vilinvil** [comment]
Issue был признан не багом, т.к. это в большей степени неоднозначность с точки зрения UX
