### ISSUE TITLE
Работяги из Чайхоны. Профиль донатера & автора. Дублирование запросов на сервер в "статусе" и "об авторе"

### ISSUE THREAD

**Issue by Vilinvil** [VK-BMSTU-QA/homework-2-spring-2024#199]
**Приоритет:** Средний
**Окружение:** Chrome Version 122.0.6261.111 (Official Build) (64-bit)
**URL:** https://my-kopilka.ru/profile26 или https://my-kopilka.ru/profile24

**Шаги воспроизведения:**
1. Войти аккаунта донатера https://my-kopilka.ru/login (у автора тоже баг)
Логин: vilin_author или vilin_donater
Пароль: 1234!@#$qwerQWER
2. Перейти на страницу профиля https://my-kopilka.ru/profile24
3. Нажать на шестеренку редактирования "статуса" или "об авторе".
4. Нажать "ок" 
5. Повторит несколько раз 3,4 пункты.

**Фактический результат:**
При нажатии ок в всплывающем окне "статуса" или "об авторе" более 1 раза, кол-во запросов отправляемых на сервер за раз начинает расти на 1 с каждым разом (2,3,4...).

![bug_multi_req_status](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/98636591/7949b2e7-2d76-42f9-bc5d-c2d158479537)

**Ожидаемый результат:**
Должен быть один запрос всегда

**Comment by SanExpett** [comment]
апрув

**Comment by M0rdovorot** [comment]
апрув

**Comment by sachatarba** [comment]
апрув
