### ISSUE TITLE
Работяги из Чайхоны. Профиль автора. Отображение нерабочей функциональности(Цели, Лента, Медиа)

### ISSUE THREAD

**Issue by Vilinvil** [VK-BMSTU-QA/homework-2-spring-2024#200]
**Приоритет:** Средний
**Окружение:** Chrome Version 122.0.6261.111 (Official Build) (64-bit)
**URL:** https://my-kopilka.ru/profile26

**Шаги воспроизведения:**
1. Войти как автор https://my-kopilka.ru/login (у автора тоже баг)
Логин: vilin_author
Пароль: 1234!@#$qwerQWER
2. Перейти на страницу профиля https://my-kopilka.ru/profile26

**Фактический результат:**
В профиле отображается "Цели" хотя нет возможности их добавить, нельзя показывать пользователям функционал, который не работает.

![bug_goals](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/98636591/e157cdb7-c19b-485e-a89a-f7df61202d04)

 Также отображаются надписи "Лента" и "Медиа" хотя никаких кнопок переключения нет.
![image](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/98636591/7efdd400-9254-4b67-a163-f968942f3921)

**Ожидаемый результат:**
Функционал скрыт или работает.

**Comment by SanExpett** [comment]
апрув

**Comment by M0rdovorot** [comment]
апрув

**Comment by alexey-ershkov** [comment]
Аппрув
