### ISSUE TITLE
Работяги из Чайхоны. Профиль автора. Отображение не рабочего функционала(Лента и Медиа)

### ISSUE THREAD

**Issue by Vilinvil** [VK-BMSTU-QA/homework-2-spring-2024#201]
**Приоритет:** Средний
**Окружение:** Chrome Version 122.0.6261.111 (Official Build) (64-bit)

**Шаги воспроизведения:**
1. Войти как автор https://my-kopilka.ru/login (у автора тоже баг)
Логин: vilin_author
Пароль: 1234!@#$qwerQWER
2. Перейти на страницу профиля https://my-kopilka.ru/profile26

**Фактический результат:**
Отображаются надписи "Лента" и "Медиа" хотя никаких кнопок переключения нет, нужно убрать медиа, чтобы не запутывать пользователя.

**Ожидаемый результат:**
Отсутствие надписей "Лента" и "Медиа".

**Comment by SanExpett** [comment]
апрув

**Comment by M0rdovorot** [comment]
апрув

**Comment by sachatarba** [comment]
апрув
