### ISSUE TITLE
Работяги из Чайхоны. Настройки профиля. Уязвимость - можно загрузить любой файл в качестве аватарки. 

### ISSUE THREAD

**Issue by Vilinvil** [VK-BMSTU-QA/homework-2-spring-2024#203]
**Приоритет:** Средний
**Окружение:** Chrome Version 122.0.6261.111 (Official Build) (64-bit)
**URL:** https://my-kopilka.ru/settings

**Шаги воспроизведения:**
1. Авторизоваться https://my-kopilka.ru/login
2. Перейти на страницу редактирования профиля https://my-kopilka.ru/settings
3. Нажать "выбрать файл".
4. Вставить файл с расширением отличным от содержимого.

**Фактический результат:**
При выборе файла другого формата, но с измененным расширением на png
  файл успешно загружается.
  Пр: исполняемый файл с расширением png

**Ожидаемый результат:**
По содержимому будет определятся разрешение файла и будет запрещать использовать не png и не jpg.

**Comment by SanExpett** [comment]
апрув

**Comment by M0rdovorot** [comment]
апрув

**Comment by sachatarba** [comment]
апрув

**Comment by alexey-ershkov** [comment]
Аппрув
