### ISSUE TITLE
Работяги из Чайхоны. Лента. Все посты приходят с датой создания 0001.01.01 00:00, следовательно, не в правильном порядке отображаются.

### ISSUE THREAD

**Issue by SanExpett** [VK-BMSTU-QA/homework-2-spring-2024#204]
Приоритет: Высокий
Окружение: Chrome Version 122.0.6261.111 (Official Build) (64-bit)

#### Шаги воспроизведения:

1. Авторизоваться https://my-kopilka.ru/login
Логин: vilin_author
Пароль: 1234!@#$qwerQWER
2. Перейти в ленту https://my-kopilka.ru/feed

#### Фактический результат
В ленте в запросе постов приходят все посты с датой создания 0001.01.01 00:00, следовательно, не в правильном порядке отображаются.
![image](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/118511246/5d60c692-633a-4ce6-ae07-d9e58931aa48)

#### Ожидаемый результат
Посты в ленте отображаются в порядке даты создания

**Comment by Vilinvil** [comment]
апрув

**Comment by M0rdovorot** [comment]
апрув

**Comment by sachatarba** [comment]
апрув
