### ISSUE TITLE
Работяги из Чайхоны. Настройки профиля. Нет сообщения об ошибке при попытки смены пароля без указания старого. 

### ISSUE THREAD

**Issue by Vilinvil** [VK-BMSTU-QA/homework-2-spring-2024#205]
**Приоритет:** Средний
**Окружение:** Chrome Version 122.0.6261.111 (Official Build) (64-bit)
**URL:**  https://my-kopilka.ru/settings

**Шаги воспроизведения:**
1. Авторизоваться https://my-kopilka.ru/login
2. Перейти на страницу редактирования профиля https://my-kopilka.ru/settings
3. Ввести новый пароль удовлетворяющий условиям:
  * 8 или более символов
  * Строчные латинские буквы
  * Заглавные латинские буквы
  * Цифры
  * Специальные символы (#?!@$%^&*-)
4. Повторить новый пароль
5. Ввести пустой пароль в поле "старый пароль" или не соответствующий установленному.

**Фактический результат:**
Перенаправляется на страницу профиля (https://my-kopilka.ru/profile24) без сообщения об ошибке.

**Ожидаемый результат:**
Остается на странице редактирования с сообщением об ошибке пример: неправильный старый пароль.

**Comment by SanExpett** [comment]
апрув

**Comment by M0rdovorot** [comment]
апрув

**Comment by sachatarba** [comment]
апрув
