### ISSUE TITLE
Работяги из Чайхоны. Настройки профиля. Не соответствующее сообщение об ошибке при попытке смена логина на не уволетворяющий требованиям.

### ISSUE THREAD

**Issue by Vilinvil** [VK-BMSTU-QA/homework-2-spring-2024#207]
**Приоритет:** Средний
**Окружение:** Chrome Version 122.0.6261.111 (Official Build) (64-bit)
**URL:**  https://my-kopilka.ru/settings 

**Шаги воспроизведения:**
1. Авторизоваться https://my-kopilka.ru/login
2. Перейти на страницу редактирования профиля https://my-kopilka.ru/settings
3. Ввод логина, неудовлетворяющего условиям:
  * Логин должен быть от 3 до 16 символов 
  * может содержать только цифры, латинские буквы и - _

**Фактический результат:**
Выводится непонятная ошибка 
![bug_login_wrong](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/98636591/6fb098cc-b47d-4611-bd61-89666f707949)

**Ожидаемый результат:**
Выводится ошибка с требованиями к логину

**Comment by SanExpett** [comment]
апрув

**Comment by M0rdovorot** [comment]
апрув

**Comment by sachatarba** [comment]
апрув
