### ISSUE TITLE
Работяги из Чайхоны. Посты. Нерабочие кнопки "комментирования" и "переслать".

### ISSUE THREAD

**Issue by SanExpett** [VK-BMSTU-QA/homework-2-spring-2024#208]
**Приоритет:** Средний
**Окружение:** Chrome Версия 121.0.6167.139 (Официальная сборка), (64 бит)
**URL:** https://my-kopilka.ru/profile2

#### Шаги воспроизведения 
1. Авторизуемся (логин - SanExpett, пароль - passworD1^^)  https://my-kopilka.ru/login 
2. Перейдем в ленту https://my-kopilka.ru/feed или на профиль какого нибудь автора https://my-kopilka.ru/profile2
3. Выберем какой нибудь пост

#### Фактический результат 
В постах отображаются значки "комментирования" и "переслать", выглядят как кнопки, но при нажатии ничего не происходит.
![image](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/118511246/6e52f6a0-7c72-41c3-b5b4-104256fc010f)

#### Ожидаемый результат 
Переход в комментарии при нажатии на иконку "комментирования", пересылка поста при нажатии на иконку "переслать".

**Comment by Vilinvil** [comment]
апрув

**Comment by M0rdovorot** [comment]
апрув

**Comment by sachatarba** [comment]
апрув

**Comment by alexey-ershkov** [comment]
Аппрув
