### ISSUE TITLE
Работяги из Чайхоны. Настройки профиля. При успешном изменение профиля нет сообщения.

### ISSUE THREAD

**Issue by Vilinvil** [VK-BMSTU-QA/homework-2-spring-2024#209]
**Приоритет:** Низкий
**Окружение:** Chrome Version 122.0.6261.111 (Official Build) (64-bit)

**Шаги воспроизведения:**
1. Авторизоваться https://my-kopilka.ru/login
2. Перейти на страницу редактирования профиля https://my-kopilka.ru/settings
3. Поменять например логин и нажать ок.
4. Происходит перенаправление на страницу профиля https://my-kopilka.ru/profile24

**Фактический результат:**
Нет сообщения  об успешном изменении профиля. 

**Ожидаемый результат:**
Есть сообщение об успешном изменении профиля, чтобы пользователям было понятнее, что все ок.

**Comment by SanExpett** [comment]
апрув

**Comment by M0rdovorot** [comment]
апрув

**Comment by Vilinvil** [comment]
Issue был признан не багом, т.к. это больше неодназночность UI, чем баг
