### ISSUE TITLE
Работяги из Чайхоны. Пост. Автору не видны уровни доступа у постов в ленте. 

### ISSUE THREAD

**Issue by Vilinvil** [VK-BMSTU-QA/homework-2-spring-2024#211]
**Приоритет:** Средний
**Окружение:** Chrome Version 122.0.6261.111 (Official Build) (64-bit)

**Шаги воспроизведения:**
1. Зайти как автор https://my-kopilka.ru/login
Логин: vilin_author

Пароль: 1234!@#$qwerQWER
2. Перейти в профиль https://my-kopilka.ru/profile26

**Фактический результат:**
В отображении поста для автора нет информации об уровне подписки для доступа к нему, видно только в меню редактирования.

![bug_view_level_subscription_in_post](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/98636591/4668c013-7620-4c5a-ba20-bee4d160fc7e)

**Ожидаемый результат:**
Прямо в ленте подписывается, с какого уровня подписчики увидят этот пост.

**Comment by SanExpett** [comment]
апрув

**Comment by M0rdovorot** [comment]
апрув

**Comment by Vilinvil** [comment]
Был признан не багом, а не доработкой с точки зрения UX
