### ISSUE TITLE
Работяги из Чайхоны. Пост. При редактировании поста, если перетянуть картинку, она продублируется. 

### ISSUE THREAD

**Issue by SanExpett** [VK-BMSTU-QA/homework-2-spring-2024#213]
**Приоритет:** Средний
**Окружение:** Chrome Версия 121.0.6167.139 (Официальная сборка), (64 бит)
**URL:** https://my-kopilka.ru/newpost

#### Шаги воспроизведения
1. Авторизоваться, как автор (логин - SanExpet-author, пароль - passworD1^^)  https://my-kopilka.ru/login
2. Создадим новый пост с картинкой https://my-kopilka.ru/newpost
3. Перейти на страницу редактирования этого поста https://my-kopilka.ru/editpost29
![image](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/118511246/d6cdda16-d06e-4af4-ab8a-82d5911a6e51)
4. Перетянуть картинку в поле "Текст поста"

#### Фактический результат 
Картинка дублируется и удалить её нельзя (у продублированной картинки нет кнопки удалить), но если нажать кнопку "опубликовать", то продублированная картинка исчезнет. 
![image](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/118511246/490022b4-5e66-44c5-89ab-560d0fd46967)

#### Ожидаемый результат 
Фото поменяло местоположение.

**Comment by Vilinvil** [comment]
Стоит добавить, что она дублируется, но при публикации исчезает и продублированную фотку нельзя удалить, т.к. у нее нет кнопки "удалить", что дополнительно запутывает.

**Comment by SanExpett** [comment]
поправил

**Comment by Vilinvil** [comment]
апрув

**Comment by M0rdovorot** [comment]
апрув

**Comment by sachatarba** [comment]
апрув

**Comment by alexey-ershkov** [comment]
Аппрув
