### ISSUE TITLE
Работяги из чайхоны. Донаты. Сообщение в донатах нигде не отображаются.

### ISSUE THREAD

**Issue by M0rdovorot** [VK-BMSTU-QA/homework-2-spring-2024#216]
**Приоритет:** Средний
**Окружение:** Chrome Version 122.0.6261.111 (Official Build) (64-bit)
**URL:** Любая страница автора ([Пример](https://my-kopilka.ru/profile28))

**Шаги воспроизведения:**
1.  Авторизоваться https://my-kopilka.ru/login
Логин: Suber 
Пароль: Suber888*
2. Перейти на страницу автора https://my-kopilka.ru/profile28
3. Нажать кнопку "Отправить донат"
![image](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/113305376/29702fc7-a038-498b-95a1-3a18ac7cb087)
4. Написать сумму доната больше десяти, написать любое сообщение
![image](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/113305376/82d3a419-a22a-4f8a-be48-2269e12b7f2e)
5. Подтвердить оплату. Для этого выбрать способ оплаты банковской картой
Номер карты 5555 5555 5555 4444
Дата истечения: 12/25 
CVV: 123
![image](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/113305376/0e25275b-d1d8-41dd-85d6-3a88c30a1040)

**Фактический результат:**
Авторизовавшись за донатера, введенное сообщение нигде не найти
Авторизовавшись за автора, введенное сообщение нигде не найти. Для этого разлогиниться, авторизоваться за автора https://my-kopilka.ru/login
Логин: Author
Пароль: Author8*

**Ожидаемый результат:**
Либо отсутствие поля для сообщений в форме донатов, либо наличие где-нибудь списка сообщений от донатов

**Comment by Vilinvil** [comment]
Только проверить, что окружение, т.е. браузер дейстивтельно такой

**Comment by SanExpett** [comment]
апрув

**Comment by sachatarba** [comment]
апрув

**Comment by alexey-ershkov** [comment]
Аппрув
