### ISSUE TITLE
Работяги из Чайхоны. Подписки. Отображается интерфейс неподписанного пользователя после оформления подписки. Застывший счетчик подписчиков

### ISSUE THREAD

**Issue by M0rdovorot** [VK-BMSTU-QA/homework-2-spring-2024#217]
**Приоритет:** Высокий
**Окружение:** Chrome Version 122.0.6261.111 (Official Build) (64-bit)
**URL:** Страница некоторого автора ([Пример](https://my-kopilka.ru/profile2))

**Шаги воспроизведения:**
1. Авторизоваться https://my-kopilka.ru/login
Логин: Suber
Пароль: Suber888*
2. Перейти на страницу автора https://my-kopilka.ru/profile2
3. Нажать кнопку "Отслеживать"
![image](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/113305376/06f4fa28-914d-49e8-aa86-389e2aa25b82)
4. Обновить страницу

**Фактический результат:**
![image](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/113305376/c6bb099f-38a0-4a82-a164-6140b982625c)
![image](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/113305376/52347c9d-98c3-4aad-9cb1-f482683b8620)
Запрос на подписку выполняется успешно, возвращается даже id подписки, но интерфейс выглядит, как будто подписка не оформлена, но в [ленте](https://my-kopilka.ru/feed) можно найти посты автора, на которого подписались. К тому же счетчик подписчиков застывает на 1
![image](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/113305376/66929620-15f0-4dec-870c-a4f357243949)

**Ожидаемый результат:**
После оформления подписки должна быть кнопка "Перестать отслеживать", счет подписчиков увеличится на единицу 
![image](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/113305376/43640c3d-9dcc-4711-a5d3-bcaf68bf099b)

**Comment by Vilinvil** [comment]
Апрув, только проверить, что окружение, т.е. браузер дейстивтельно такой.

**Comment by SanExpett** [comment]
апрув

**Comment by sachatarba** [comment]
апрув

**Comment by alexey-ershkov** [comment]
аппрув

**Comment by alexey-ershkov** [comment]
Аппрув
