### ISSUE TITLE
Работяги из Чайхоны. Аналитика. Можно открыть аналитику для донатера

### ISSUE THREAD

**Issue by M0rdovorot** [VK-BMSTU-QA/homework-2-spring-2024#218]
**Приоритет:** Низкий
**Окружение:** Chrome Version 122.0.6261.111 (Official Build) (64-bit)
**URL:** https://my-kopilka.ru/statistic

**Шаги воспроизведения:**
1. Авторизоваться как донатер https://my-kopilka.ru/login
Логин: Suber
Пароль: Suber888*
2. Перейти на [страницу аналитики](https://my-kopilka.ru/statistic)

**Фактический результат:**
Отображается страница аналитики с нулевыми значениями
![image](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/113305376/3b7bf571-a57b-42d5-8940-4d24e615aa24)

**Ожидаемый результат:**
Вывести предупреждение, что пользователь авторизован как донатер, соответственно, нельзя отобразить статистику

**Comment by Vilinvil** [comment]
Апрув, только проверить, что окружение, т.е. браузер дейстивтельно такой.

**Comment by SanExpett** [comment]
апрув

**Comment by sachatarba** [comment]
апрув

**Comment by alexey-ershkov** [comment]
Аппрув
