### ISSUE TITLE
Работяги из Чайхоны. Navbar. Иконка автора отображается в неправильном месте.

### ISSUE THREAD

**Issue by Vilinvil** [VK-BMSTU-QA/homework-2-spring-2024#219]
**Приоритет:** Низкий
**Окружение:** Firefox 123.0 (64-bit)
**URL:** все страницы доступные авторизованному пользователю

**Шаги воспроизведения:**
1. Авторизоваться https://my-kopilka.ru/login
2. Перейти в ленту https://my-kopilka.ru/feed

**Фактический результат:**
Иконка автора смещена в центр 

![bug_avatar_positon](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/98636591/78c39439-ec43-4cf2-80ec-8b4aec57015c)

**Ожидаемый результат:**
Иконка автора расположена справого края.

**Comment by SanExpett** [comment]
апрув

**Comment by sachatarba** [comment]
апрув

**Comment by M0rdovorot** [comment]
аппрув

**Comment by alexey-ershkov** [comment]
аппрув
