### ISSUE TITLE
Работяги из Чайхоны. Тег. Не отображаются посты по тегам

### ISSUE THREAD

**Issue by sachatarba** [VK-BMSTU-QA/homework-2-spring-2024#220]
**Приоритет**: высокий
**Окружение**: Chrome Version 122.0.6261.95 (Official Build) (64-bit)
**URL**: https://my-kopilka.ru/feed
**Шаги воспроизведения**.

1. Создать аккаунт / авторизоваться за автора
2. Создать пост с тегом (можно уже существующим)
3. Создать аккаунт / авторизоваться за донатера
4. Перейти на страницу автора
5. Найти созданный пост
6. Перейти по тегу

**Фактический результат**:
в ленте постов по тегу не отображаются посты авторов, на которых нет подписки
![image-19](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/92438001/710aec72-8f71-4ed7-9ec9-bed0b9f90603)
![image-20](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/92438001/83288412-a3ff-454f-acf6-2f69e977b25f)
**Ожидаемый результат**:
в ленте отображаются все посты, имеющие данный тег

**Comment by SanExpett** [comment]
апрув

**Comment by Vilinvil** [comment]
Апрув, только проверь, что у тебя точно такое окружение Chrome Version 122.0.6261.111 (Official Build) (64-bit)

**Comment by M0rdovorot** [comment]
аппрув

**Comment by Vilinvil** [comment]
Добавь в название "Тег"
вот так "Работяги из Чайхоны. Тег. ..."

**Comment by alexey-ershkov** [comment]
Аппрув
