### ISSUE TITLE
Работяги из Чайхоны. Тег. Неправильная дата в ленте постов по тегу

### ISSUE THREAD

**Issue by sachatarba** [VK-BMSTU-QA/homework-2-spring-2024#221]
**Приоритет**: высокий
**Окружение**: Chrome Version 122.0.6261.95 (Official Build) (64-bit)
**Шаги воспроизведения**.

1. Создать аккаунт / авторизоваться за автора
2. Создать пост с тегом (можно уже с существующим)
5. Найти созданный пост
6. Перейти по тегу

**Фактический результат**:
в ленте постов по тегу у постов неправильная дата
![image-13](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/92438001/ec44261e-c53f-4fcb-a31e-39e211b09931)

**Ожидаемый результат**:
в ленте отображаются посты с правильной датой

**Comment by sachatarba** [comment]
Это разные страницы и запросы к серверу (тут лента по тегу, а не по подписке), наверное, это все такие другой баг репорт

**Comment by Vilinvil** [comment]
Ладно, давай оставим, не совсем уверен, как оформлять такие похожие репорты лучше, в один с упоминанием всех случаев или в разные. 
Апрув

**Comment by M0rdovorot** [comment]
аппрув

**Comment by alexey-ershkov** [comment]
Аппрув

**Comment by SanExpett** [comment]
апрув

**Comment by sachatarba** [comment]
Объединён с https://github.com/VK-BMSTU-QA/homework-2-spring-2024/issues/183
