### ISSUE TITLE
Работяги из Чайхоны. Тег. Недетерминированный порядок постов в ленте по тегам

### ISSUE THREAD

**Issue by sachatarba** [VK-BMSTU-QA/homework-2-spring-2024#222]
**Приоритет**: высокий
**Окружение**: Chrome Version 122.0.6261.95 (Official Build) (64-bit)
**Шаги воспроизведения**.

1. Создать аккаунт / авторизоваться за автора
2. Создать пост с тегом (можно уже существующим)
3. Найти созданный пост
4. Перейти по тегу

**Фактический результат**:
в ленте постов по тегу посты отображаются не в детерминированном хронологическом порядке.
![image-16](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/92438001/e4b100ef-c3b0-4272-a1c4-b857fd68c0f0)
![image-17](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/92438001/85647965-467d-4091-bfb6-c675b9307725)
**Ожидаемый результат**:
в ленте отображаются все посты с заданным тегом в хронологическом порядке их создания

**Comment by Vilinvil** [comment]
https://github.com/VK-BMSTU-QA/homework-2-spring-2024/issues/204
Уже есть аналогичный issues
Я перенес в другой раздел эту багу, т.к. это не относится к тегам.
Смотри пр https://github.com/VK-BMSTU-QA/homework-1-spring-2024/pull/13/files
и комменты там. Этот issues нужно удалит

**Comment by sachatarba** [comment]
Это разные страницы и запросы к серверу (тут лента по тегу, а не по подписке), наверное, это все такие другой баг репорт

**Comment by alexey-ershkov** [comment]
Аппрув

**Comment by SanExpett** [comment]
апрув

**Comment by sachatarba** [comment]
Объединён с https://github.com/VK-BMSTU-QA/homework-2-spring-2024/issues/183
