### ISSUE TITLE
Работяги из Чайхоны. Тег. Недетерминированный порядок тегов в посте

### ISSUE THREAD

**Issue by sachatarba** [VK-BMSTU-QA/homework-2-spring-2024#223]
**Приоритет**: низкий
**Окружение**: Chrome Version 122.0.6261.95 (Official Build) (64-bit)
**URL**: https://my-kopilka.ru/profile1
**Шаги воспроизведения**.

1. Создать аккаунт / авторизоваться за автора
2. Создать пост с тегом (можно уже существующим)
3. Найти созданный пост
4. Перезапустить страницу
5. Снова найти пост

**Фактический результат**:
порядок тегов в посте каждый раз разный
![image-14](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/92438001/ea5ca6e8-5d1e-409d-ac30-6aee624ec30e)
![image-15](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/92438001/9d4f1d6a-3ff6-45b6-9c50-3c9d4d6bcd64)

**Ожидаемый результат**:
порядок тегов одинаковый

**Comment by Vilinvil** [comment]
Апрув, только проверь, что у тебя точно такое окружение: Chrome Version 122.0.6261.111 (Official Build) (64-bit)

**Comment by M0rdovorot** [comment]
аппрув

**Comment by Vilinvil** [comment]
Добавь в название "Тег"
вот так "Работяги из Чайхоны. Тег. ..."

**Comment by alexey-ershkov** [comment]
Аппрув

**Comment by SanExpett** [comment]
апрув
