### ISSUE TITLE
Фанаты Ёлки. Регистрация. Имя пользователя. При замене уже существующего имени ошибка не исчезает.

### ISSUE THREAD

**Issue by tomsuliana** [VK-BMSTU-QA/homework-2-spring-2024#32]
**URL:** https://prinesy-poday.ru/
**Приоритет:** Major
**Окружение:** Linux, Google Chrome Version 121.0.6167.160

**Шаги воспроизведения:**

1. Нажать кнопку “Войти” на главной странице
2. Нажать кнопку “Зарегистрироваться”
3. Ввести поле имени имя, которое уже есть в базе данных (и заполнить остальные поля)
4. Нажать кнопку “Далее” 
5. После увиденного сообщения о том, что такое имя уже существует, нажать стрелку назад и поменять имя на новое
6. Нажать кнопку “Далее”

**Текущий результат:** появляется ошибка о том, что такое имя уже существует 
**Ожидаемый результат:** регистрация проходит без возникновения данной ошибки 
**Доп. информация:** ошибка исчезает только после повторного нажатия кнопки "Зарегистрироваться" и регистрация проходит нормально
![zamenauser](https://github.com/VK-BMSTU-QA/homework-2-spring-2024/assets/114855427/c4505511-6232-4d47-8b31-0291b73ffbd3)

**Comment by wizardOfOz21** [comment]
в третьем шаге пропущено "в"

**Comment by Dellvin** [comment]
аппрув
