### ISSUE TITLE
MovieHub. Страница актёра. Не работает удаление актёра из списка любимых актёров. После обновления страницы список возвращается в состояние до удаления.

### ISSUE THREAD

**Issue by JuFnd** [VK-BMSTU-QA/homework-2-spring-2024#43]
Приоритет: высокий

URL: https://movie-hub.ru/actor/1

Как воспроизвести:
1. Авторизоваться
2. Переходим на страницу любого актёра(URL)
3. Жмём на флажок добавления в список любимых актёров
4. Жмём ещё раз в попытке удалить актёра из списка, но при обновлении страницы актёр всё ещё в списке, а флажок всё ещё жёлтый.

Ожидаемый результат: При нажатии на флажок актёр удаляется из списка любимых актёров
Фактический результат: После нажатия при обновлении страницы актёр остаётся в списке любимых актёров.

**Comment by BeeHeather** [comment]
*В названии - Не работает

**Comment by Gokert** [comment]
апрув

**Comment by JuFnd** [comment]
аппрув

**Comment by AlfaIV** [comment]
аппрув

**Comment by BeeHeather** [comment]
Аппрув

**Comment by JuFnd** [comment]
Дубль
