### ISSUE TITLE
Фанаты Ёлки. Промокоды. Промокод не стирается после оформления заказа.

### ISSUE THREAD

**Issue by HallowAz** [VK-BMSTU-QA/homework-2-spring-2024#94]
### URL

-  https://prinesy-poday.ru/cart

### Приоритет

- major

### Окружение

- Браузер Google Chrome 121.0.6167.185
- ОС Windows 10 

### Описание 

При оформлении заказа с промокодом на бесплатную сумму доставки и повторном заходе в корзину, промокод не стирается, а сумма доставки меняется с 0 на 0.

#### Шаги воспроизведения

* Авторизоваться
* Открыть страницу любого ресторана
* Добавить любой продукт в корзину
* Открыть корзину
* Применить промокод "PRINESYFREE"
* Выбрать любой способ оплаты 
* Нажать кнопку "Оформить заказ"
* После редиректа на историю заказов, вернутся на страницу корзины

#### Текущее поведение

Промокод продолжает действовать. Сумма доставки меняется с 0 на 0

#### Ожидаемое поведение

Промокод применяется всего один раз, после этого перестаёт действовать

**Comment by kek-flip** [comment]
Аппрув

**Comment by wizardOfOz21** [comment]
Тут ещё баг с тем, что можно промокод применить к пустой корзине, можно его отдельно вынести

**Comment by wizardOfOz21** [comment]
В описании "на бесплатную доставку" и "повторном переходе"

**Comment by tomsuliana** [comment]
аппрув

**Comment by HallowAz** [comment]
Объединил с багом #97
