### ISSUE TITLE
Фанаты Ёлки. Промокоды. Использование промокода любое количество раз.

### ISSUE THREAD

**Issue by HallowAz** [VK-BMSTU-QA/homework-2-spring-2024#95]
### URL

-  https://prinesy-poday.ru/cart

### Приоритет

- critical

### Окружение

- Браузер Google Chrome 121.0.6167.185
- ОС Windows 10 

### Описание 

Промокод "PRINESYFREE" можно использовать сколько угодно раз

#### Шаги воспроизведения

* Авторизоваться
* Открыть страницу любого ресторана
* Добавить любой продукт в корзину
* Открыть корзину
* Выбрать любой способ оплаты 
* Применить промокод "PRINESYFREE"
* Открыть корзину
* Отменить промокод
 * Открыть страницу любого ресторана
* Добавить любой продукт в корзину
* Открыть корзину
* Применить промокод "PRINESYFREE"
 
#### Текущее поведение

Промокод применяется повторно.

#### Ожидаемое поведение

Запрет на применение промокода. Появляется сообщение о том, что промокод уже использовался.

**Comment by kek-flip** [comment]
Уже был баг с повторным применением промокода - #97 
Расширь баг-репорт #97 на все промокоды

**Comment by wizardOfOz21** [comment]
А в чем баг, если промокод сначала отменяется а потом снова применяется? Это же норм

**Comment by tomsuliana** [comment]
> Уже был баг с повторным применением промокода - #97 Расширь баг-репорт #97 на все промокоды

Согласна

**Comment by HallowAz** [comment]
Объединил с багом #97
